require 'spec_helper'

describe IsHuman do
  before do
    IsHuman.salt = 'blah'
    @is_human = IsHuman.new
    #puts "#{@is_human.question} == #{@is_human.answer}"
  end

  it "generates three random numbers between 2 and 10" do
    @is_human.numbers.count.should == 3
    @is_human.numbers[0].should be_between(2, 10)
    @is_human.numbers[1].should be_between(2, 10)
    @is_human.numbers[2].should be_between(2, 10)
  end

  it "selects two categories that do not equal each other" do
    @is_human.primary_category.should match /flowers|fruit|animals|clothes/
    @is_human.secondary_category.should match /flowers|fruit|animals|clothes/
    @is_human.primary_category.should_not == @is_human.secondary_category
  end

  it "sums the first two numbers in sequence to form the answer" do
    @is_human.numbers = [4, 5, 10]
    @is_human.answer.should == 9
  end

  it "generates a question containing the various numbers and categories" do
    @is_human.items = ['8 apples', '5 bananas', '2 hats']
    @is_human.primary_category = :fruits
    @is_human.question.should == "If I had 8 apples, 5 bananas and 2 hats. How many fruits do I have?"
  end

  it "generates an SHA1 hash of the answer combined with the secret salt" do
    @is_human.numbers = [4, 5, 10]
    @is_human.hashed_answer.should == "a42198ba9a8c4111a7912c9a21c358df89596b94"
  end

  it "checks that a given answer matches the hash generated by a previous question" do
    @is_human.correct?(9, "a42198ba9a8c4111a7912c9a21c358df89596b94").should be_true
  end
end